project:
  type: book
  output-dir: _book

execute:
  freeze: auto

book:
  title: "Global wetland and peatland modelling"
  subtitle: "A tutorial introducing the TOPMODEL-based wetland and peatland model DYPTOP"
  author: "Benjamin Stocker"
  date: "2025/03/20"
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - fflooded.qmd
    - wetlands.qmd
    - peatlands.qmd
    - exercises.qmd
    - references.qmd
  favicon: "figures/favicon.ico"
  twitter-card: true
  search: true
  repo-url: https://github.com/geco-bern/dyptop_tutorial
  sharing: [twitter, facebook]
  navbar:
    title: " "
    logo: "images/logo.png"
    background: "#3A3A3A"
    search: true
    right:
      - text: "Home"
        file: index.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
