# Exercises

## Completing DYPTOP

The description of the model in @sec-fflooded is incomplete. An additional point is considered for determining the flooded area fraction as a function of the water table depth in the work by @stocker14dyptop. Which one? Complement the model and revise @fig-fflooded_wtd, visualising the additional constraint.

You can find all code shown and data used in this tutorial [here](https://github.com/geco-bern/dyptop_tutorial) (code in `.qmd` files stored under `book/`, data in `data/`). 


## Improving the global peatland prediction

The predicted global distribution of the actual peatland area fraction shown in @fig-fpeat_act some major northern peatland complexes, including the Hudson Bay Lowland and the West Siberian Lowlands. In other regions, the map suggests excessive peatland areas (e.g., Amazon). Modify model parameters to improve the correspondence between predicted and observed global peatland areas. As observations, you may consider the global peatland map PEATMAP, shown e.g., [here](https://geco-bern.github.io/les/globalcarbonpatterns.html#fig-peatland_map). 

:::{.callout-tip} 

### Pro-tip

Fork and clone the GitHub repository and open it as a project in RStudio. This lets you run the code shown in the tutorial and render the HTML output hosted on the tutorial's website. 

:::